title: James Dunham
url: "https://jdunham.io"
baseurl: #

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "© 2019 James Dunham, design credit ankitsultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Github"
   link: "https://github.com/jamesdunham"

